name: Autocorrect 'rubocop-composite-action'

on: check_run

jobs:
  autocorrect:
    name: Setup with rubocop version as argument
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      shell: bash
      run: |
        echo "$GITHUB_CONTEXT" | tee github.json


