name: Test 'rubocop-composite-action' autocorrect feature
on:
  push:
    branches: [develop]
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  autocorrect-test:
    name: Test autocorrect
    runs-on: ubuntu-latest

    steps:
    - name: Checkout for PR
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}  # Checkout the PR branch instead of the merge commit

    - name: Checkout for push
      if: ${{ github.event_name != 'pull_request' }}
      uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2

    - uses: actions/setup-python@v5
      with:
        python-version: 3.12.2

    - name: Run rubocop
      id: rubocop
      uses: ./
      with:
        autocorrect: true
        commit-auto-correct: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TEST_DONOT_THROW: true   # For the in-repo tests, I don't want to fail the workflow
